"""The technique → detector → fixture coverage matrix.

Generated from the detector registry and the fixture corpus, never hand-written.
A hand-maintained coverage table is a document that starts true and becomes a
lie on the first commit nobody remembers to update; this one cannot drift,
because it is derived.

What it is honestly measuring: which ATT&CK techniques Bishop has a
*deterministic detector* for, and which of those are exercised by a labelled
fixture. A technique with a detector and no fixture is untested coverage — worth
knowing, and the matrix says so rather than counting it as green.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field

from bishop.attck.catalogue import Technique, load_catalogue
from bishop.detectors.base import registry


@dataclass(slots=True)
class TechniqueCoverage:
    technique: Technique
    detectors: list[str] = field(default_factory=list)
    fixtures: list[str] = field(default_factory=list)

    @property
    def status(self) -> str:
        if self.detectors and self.fixtures:
            return "covered"
        if self.detectors:
            return "untested"
        return "none"


@dataclass(slots=True)
class CoverageMatrix:
    attack_version: str
    entries: list[TechniqueCoverage] = field(default_factory=list)
    invalid_hints: list[tuple[str, str]] = field(default_factory=list)

    def by_tactic(self) -> dict[str, list[TechniqueCoverage]]:
        grouped: dict[str, list[TechniqueCoverage]] = defaultdict(list)
        for entry in self.entries:
            for tactic in entry.technique.tactic_names or ("unmapped",):
                grouped[tactic].append(entry)
        return dict(sorted(grouped.items()))

    @property
    def covered(self) -> list[TechniqueCoverage]:
        return [e for e in self.entries if e.status == "covered"]

    @property
    def untested(self) -> list[TechniqueCoverage]:
        return [e for e in self.entries if e.status == "untested"]

    def summary(self) -> str:
        return (
            f"{len(self.covered)} techniques covered by a detector and exercised by a fixture, "
            f"{len(self.untested)} with a detector but no fixture, "
            f"against ATT&CK v{self.attack_version}"
        )


def build_matrix(fixture_techniques: dict[str, list[str]] | None = None) -> CoverageMatrix:
    """Build the matrix from the detector registry and fixture labels.

    `fixture_techniques` maps alert ID to the techniques its label claims. Pass
    `None` to build the detector half only, which is what the docs generator
    does when no corpus is present.
    """
    catalogue = load_catalogue()
    matrix = CoverageMatrix(attack_version=catalogue.attack_version)

    by_technique: dict[str, TechniqueCoverage] = {}

    for spec in registry().values():
        for hint in spec.techniques:
            result = catalogue.validate([hint])
            if result.rejected:
                matrix.invalid_hints.append((spec.name, hint))
                continue
            technique = result.accepted[0]
            entry = by_technique.get(technique.id)
            if entry is None:
                entry = TechniqueCoverage(technique=technique)
                by_technique[technique.id] = entry
            if spec.name not in entry.detectors:
                entry.detectors.append(spec.name)

    for alert_id, techniques in (fixture_techniques or {}).items():
        for hint in techniques:
            result = catalogue.validate([hint])
            if result.rejected:
                continue
            technique = result.accepted[0]
            entry = by_technique.get(technique.id)
            if entry is None:
                entry = TechniqueCoverage(technique=technique)
                by_technique[technique.id] = entry
            if alert_id not in entry.fixtures:
                entry.fixtures.append(alert_id)

    matrix.entries = sorted(by_technique.values(), key=lambda e: e.technique.id)
    return matrix


def render_markdown(matrix: CoverageMatrix) -> str:
    """Render the matrix as the body of `docs/COVERAGE.md`."""
    lines = [
        "<!-- Generated by `just coverage`. Do not edit by hand. -->",
        "",
        "# Coverage",
        "",
        f"Technique coverage against **MITRE ATT&CK v{matrix.attack_version}**.",
        "",
        matrix.summary() + ".",
        "",
        "`covered` means a deterministic detector maps to the technique *and* a labelled",
        "fixture exercises it. `untested` means the detector exists but no fixture in the",
        "golden set produces it — real coverage, unproven coverage. The distinction is the",
        "point of the table.",
        "",
    ]

    if matrix.invalid_hints:
        lines += [
            "> **Invalid technique hints found.** These detectors propose IDs that are not in",
            "> the bundle, which is a bug:",
            "",
        ]
        lines += [f"> - `{detector}` → `{hint}`" for detector, hint in matrix.invalid_hints]
        lines += [""]

    for tactic, entries in matrix.by_tactic().items():
        lines += [
            f"## {tactic}",
            "",
            "| Technique | Detectors | Fixtures | Status |",
            "|---|---|---|---|",
        ]
        for entry in sorted(entries, key=lambda e: e.technique.id):
            detectors = ", ".join(f"`{d}`" for d in entry.detectors) or "—"
            fixtures = ", ".join(f"`{f}`" for f in sorted(entry.fixtures)) or "—"
            technique = entry.technique
            link = f"[{technique.id}]({technique.url})" if technique.url else technique.id
            lines.append(f"| {link} {technique.name} | {detectors} | {fixtures} | {entry.status} |")
        lines.append("")

    lines += [
        "## What this table does not say",
        "",
        "Coverage of a technique is not detection of every implementation of it. Bishop's",
        "`persistence` detector matches known reboot-surviving mechanisms; an attacker using",
        "one that is not in `catalogues.py` produces no signal, and the matrix would still",
        "show T1547.001 as covered. Read this as a map of what has been *tried*, not a",
        "guarantee of what would be *caught*.",
        "",
    ]
    return "\n".join(lines)
