#!/usr/bin/env bash
# Record docs/demo/demo.gif — the animated version of the README's header image.
#
# The static SVGs beside it are generated from real command output by
# scripts/render_terminal_svg.py, so they cannot drift from what Bishop prints.
# A GIF cannot be regenerated by CI, so it is produced here, deliberately, by a
# person.
#
# Needs `vhs` (https://github.com/charmbracelet/vhs):
#     brew install vhs        # macOS
#     winget install charmbracelet.vhs
#     go install github.com/charmbracelet/vhs@latest
#
# Then:  ./scripts/record_demo.sh

set -euo pipefail
cd "$(dirname "$0")/.."

if ! command -v vhs >/dev/null 2>&1; then
  echo "vhs is not installed — see the header of this script." >&2
  exit 1
fi

mkdir -p docs/demo

cat > /tmp/bishop-demo.tape <<'TAPE'
Output docs/demo/demo.gif

Set FontSize 15
Set Width 1180
Set Height 760
Set Theme "Github Dark"
Set Padding 18
Set TypingSpeed 30ms

Type "just demo"
Sleep 400ms
Enter
Sleep 9s

# The run stops at the human gate. Approve only the reversible actions —
# the point of the demo is that the irreversible ones need a decision.
Type "s"
Enter
Sleep 6s

Type "just eval-holdout"
Sleep 400ms
Enter
Sleep 8s
TAPE

vhs /tmp/bishop-demo.tape
echo "wrote docs/demo/demo.gif"
